const DJ_CONFIG = {
  version: 'V107',
  product: 'Maestro V',
  brand: 'Alpha Omega Collective',
  scenes: [
    { id: 'matrix', label: 'Matrix Coding' },
    { id: 'codeglitch', label: 'Code Glitch Terminal' },
    { id: 'constellation', label: 'Data Constellation' },
    { id: 'dna', label: 'DNA Oscilloscope' },
    { id: 'orbit', label: 'Orbit Geometry' },
    { id: 'mobius', label: 'Mobius Galaxy' },
    { id: 'obsidian', label: 'Obsidian Graph' },
    { id: 'missile', label: 'Pixel Missile Barrage' },
    { id: 'laser', label: 'Laser Perspective' },
    { id: 'chladni', label: 'Chladni Plate Resonance' },
    { id: 'chladnicyber', label: 'Cyber Chladni Nexus' },
    { id: 'slash', label: 'Spectrograph' },
    { id: 'atomic', label: 'Atomic Viral Matrix' },
    { id: 'iris', label: 'Iris Kaleidoscope' },
    { id: 'firework', label: 'Firework Multi-Burst Grid' },
    { id: 'hybrid', label: 'Hybrid Mix' }
  ],
  palettes: [
    { name: 'Cyber Cyan', a: '#79f7ff', b: '#42a5ff', c: '#ff2d8f' },
    { name: 'Toxic Matrix', a: '#8cff77', b: '#00ffbb', c: '#f7ff6b' },
    { name: 'Infra Violet', a: '#b76bff', b: '#ff2d8f', c: '#79f7ff' },
    { name: 'Amber Blue', a: '#ffc857', b: '#2ec4ff', c: '#ff5d73' },
    { name: 'Laser Red', a: '#ff334d', b: '#ff9f1c', c: '#79f7ff' },
    { name: 'Nightclub Neon', a: '#00f7ff', b: '#ff49d6', c: '#ffe45e' },
    { name: 'Ultraviolet Club', a: '#d48bff', b: '#45f0df', c: '#ff6b6b' }
  ],
  globalControls: [
    { id: 'density', label: 'Density', min: 20, max: 260, step: 1, value: 150 },
    { id: 'speed', label: 'Speed', min: 0.2, max: 4, step: 0.1, value: 1.2 },
    { id: 'glow', label: 'Glow', min: 0, max: 100, step: 1, value: 34 },
    { id: 'pulse', label: 'Pulse', min: 0, max: 120, step: 1, value: 64 },
    { id: 'lineWeight', label: 'Line Weight', min: 0.2, max: 4, step: 0.1, value: 0.9 },
    { id: 'lineOpacity', label: 'Line Opacity', min: 5, max: 100, step: 1, value: 26 },
    { id: 'pointSize', label: 'Point Size', min: 0.6, max: 10, step: 0.1, value: 3.1 },
    { id: 'pixelSize', label: 'Pixel Size', min: 1, max: 12, step: 0.1, value: 3.2 },
    { id: 'jitter', label: 'Jitter', min: 0, max: 80, step: 1, value: 20 },
    { id: 'depth', label: 'Depth', min: 0, max: 100, step: 1, value: 62 },
    { id: 'cameraZoom', label: 'Camera Zoom', min: 60, max: 160, step: 1, value: 102 },
    { id: 'cameraTilt', label: 'Camera Rotate', min: -45, max: 45, step: 1, value: 0 },
    { id: 'trails', label: 'Trails', min: 8, max: 90, step: 1, value: 22 }
  ],
  audioControls: [
    { id: 'audioGain', label: 'Mic Gain', min: 0.2, max: 4, step: 0.1, value: 1.5 },
    { id: 'bassBoost', label: 'Bass Boost', min: 0, max: 4, step: 0.1, value: 1.8 },
    { id: 'midBoost', label: 'Mid Boost', min: 0, max: 4, step: 0.1, value: 1.3 },
    { id: 'highBoost', label: 'High Boost', min: 0, max: 4, step: 0.1, value: 1.2 },
    { id: 'beatImpact', label: 'Beat Impact', min: 0, max: 120, step: 1, value: 64 },
    { id: 'beatFxStrength', label: 'Beat FX Strength', min: 0, max: 100, step: 1, value: 56 },
    { id: 'beatFxInterval', label: 'Beat FX Interval', min: 250, max: 3000, step: 50, value: 1000 }
  ],
  colorControls: [
    { id: 'hueShift', label: 'Hue Shift', min: -180, max: 180, step: 1, value: 0 },
    { id: 'saturation', label: 'Saturation', min: 40, max: 180, step: 1, value: 110 },
    { id: 'brightness', label: 'Brightness', min: 40, max: 180, step: 1, value: 108 },
    { id: 'contrast', label: 'Contrast', min: 40, max: 180, step: 1, value: 108 },
    { id: 'colorCycle', label: 'Color Cycle', min: 0, max: 100, step: 1, value: 42 },
    { id: 'gradient', label: 'Gradient Amount', min: 0, max: 100, step: 1, value: 18 },
    { id: 'gradientSpeed', label: 'Gradient Speed', min: 0, max: 100, step: 1, value: 38 },
    { id: 'gradientOpacity', label: 'Gradient Opacity', min: 0, max: 100, step: 1, value: 30 },
    { id: 'scanlines', label: 'Scanlines', min: 0, max: 100, step: 1, value: 16 }
  ],
  textFonts: [
    { id: 'hudMono', label: '01 / HUD Mono', family: "'Consolas', 'Courier New', monospace" },
    { id: 'terminal', label: '02 / Terminal', family: "'Lucida Console', 'Courier New', monospace" },
    { id: 'cyberTech', label: '03 / Cyber Tech', family: "'Orbitron', 'Segoe UI', sans-serif" },
    { id: 'matrixCode', label: '04 / Matrix Code', family: "'IBM Plex Mono', 'Courier New', monospace" },
    { id: 'neonGrid', label: '05 / Neon Grid', family: "'Eurostile', 'Trebuchet MS', sans-serif" },
    { id: 'ocrVector', label: '06 / OCR Vector', family: "'OCR A Std', 'Lucida Console', 'Courier New', monospace" },
    { id: 'monoNova', label: '07 / Mono Nova', family: "'Monaco', 'Menlo', 'Courier New', monospace" },
    { id: 'gridSlate', label: '08 / Grid Slate', family: "'Arial Narrow', 'Trebuchet MS', 'Segoe UI', sans-serif" }
  ],
  textAnimationModes: [
    { id: 'pulse', label: 'Pulse' },
    { id: 'flicker', label: 'Flicker' },
    { id: 'scan', label: 'Scan' },
    { id: 'drift', label: 'Drift' },
    { id: 'typeOn', label: 'Type-On' },
    { id: 'wave', label: 'Wave' },
    { id: 'glitch', label: 'Glitch' },
    { id: 'zoom', label: 'Zoom' },
    { id: 'spin', label: 'Spin' },
    { id: 'bounce', label: 'Bounce' }
  ],
  textControls: [
    { id: 'textSize', label: 'Text Size', min: 20, max: 180, step: 1, value: 72 },
    { id: 'textLetterSpacing', label: 'Letter Space', min: 0, max: 40, step: 1, value: 5 },
    { id: 'textLineSpacing', label: 'Line Space', min: 0.8, max: 2.4, step: 0.1, value: 1.15 },
    { id: 'textGlow', label: 'Text Glow', min: 0, max: 100, step: 1, value: 54 },
    { id: 'textRotation', label: 'Text Rotate', min: -180, max: 180, step: 1, value: 0 },
    { id: 'textOffsetX', label: 'Text Pos X', min: -100, max: 100, step: 1, value: 0 },
    { id: 'textOffsetY', label: 'Text Pos Y', min: -100, max: 100, step: 1, value: 0 },
    { id: 'textOpacity', label: 'Text Opacity', min: 0, max: 100, step: 1, value: 92 },
    { id: 'textScaleX', label: 'Text Scale X', min: 20, max: 220, step: 1, value: 100 },
    { id: 'textScaleY', label: 'Text Scale Y', min: 20, max: 220, step: 1, value: 100 },
    { id: 'textAnimationSpeed', label: 'Anim Speed', min: 10, max: 300, step: 1, value: 100 }
  ],
  sceneControls: {
    matrix: [
      { id: 'matrixLines', label: 'Line Count', min: 20, max: 180, step: 1, value: 120 },
      { id: 'matrixFallSpeed', label: 'Fall Speed', min: 0.2, max: 5, step: 0.1, value: 1.4 },
      { id: 'matrixTypingSpeed', label: 'Typing Speed', min: 0.2, max: 5, step: 0.1, value: 1.5 },
      { id: 'matrixOpacity', label: 'Opacity', min: 10, max: 100, step: 1, value: 78 },
      { id: 'matrixFontSize', label: 'Font Size', min: 8, max: 28, step: 1, value: 13 },
      { id: 'matrixLineSpacing', label: 'Line Space', min: 0.8, max: 2.2, step: 0.1, value: 1.05 },
      { id: 'matrixRandomFontSize', label: 'Rnd Font Size', min: 0, max: 100, step: 1, value: 42 }
    ],

    codeglitch: [
      { id: 'codePanelCount', label: 'Panel Count', min: 2, max: 9, step: 1, value: 5 },
      { id: 'codeStreamCount', label: 'Stream Count', min: 24, max: 220, step: 1, value: 110 },
      { id: 'codeScrollSpeed', label: 'Scroll Speed', min: 0.2, max: 4.5, step: 0.1, value: 1.6 },
      { id: 'codeSymbolSize', label: 'Symbol Size', min: 9, max: 22, step: 1, value: 13 },
      { id: 'codeGlitchAmount', label: 'Glitch Amount', min: 0, max: 100, step: 1, value: 52 },
      { id: 'codeLinkDensity', label: 'Link Density', min: 6, max: 72, step: 1, value: 32 },
      { id: 'codeWindowJitter', label: 'Window Jitter', min: 0, max: 100, step: 1, value: 38 },
      { id: 'codeRgbSplit', label: 'RGB Split', min: 0, max: 100, step: 1, value: 28 },
      { id: 'codeNoiseBlocks', label: 'Noise Blocks', min: 0, max: 120, step: 1, value: 34 },
      { id: 'codeMainFocus', label: 'Main Panel Focus', min: 0, max: 100, step: 1, value: 38 },
      { id: 'codeCursorAmount', label: 'Typing Cursors', min: 0, max: 100, step: 1, value: 44 },
      { id: 'codeScanlineStrength', label: 'Scanline Strength', min: 0, max: 100, step: 1, value: 46 },
      { id: 'codeBreachPulse', label: 'Breach Pulse', min: 0, max: 100, step: 1, value: 48 },
      { id: 'codeBinaryRain', label: 'Binary Rain', min: 0, max: 100, step: 1, value: 52 },
      { id: 'codeSnippetDensity', label: 'Snippet Density', min: 0, max: 100, step: 1, value: 54 },
      { id: 'codePanelOpacity', label: 'Panel Opacity', min: 10, max: 100, step: 1, value: 72 },
      { id: 'codeGridStrength', label: 'Grid Strength', min: 0, max: 100, step: 1, value: 44 },
      { id: 'codeCorruptionSpread', label: 'Corruption Spread', min: 0, max: 100, step: 1, value: 48 },
      { id: 'codeMode', label: 'Code Mode', min: 0, max: 4, step: 1, value: 1 }
    ],
    constellation: [
      { id: 'nodeCount', label: 'Node Count', min: 30, max: 280, step: 1, value: 160 },
      { id: 'connectDistance', label: 'Connect Dist', min: 30, max: 260, step: 1, value: 132 },
      { id: 'nodeDrift', label: 'Node Drift', min: 0, max: 100, step: 1, value: 42 },
      { id: 'constellationDotSize', label: 'Dot Size', min: 0.5, max: 8, step: 0.1, value: 1.8 },
      { id: 'constellationSymbolSize', label: 'Symbol Size', min: 1, max: 12, step: 0.1, value: 3.2 },
      { id: 'constellationCenterPull', label: 'Center Pull', min: 0, max: 100, step: 1, value: 18 },
      { id: 'constellationDriftMode', label: 'Drift Mode', min: 0, max: 2, step: 1, value: 0 },
      { id: 'constellationClusterCount', label: 'Cluster Count', min: 2, max: 6, step: 1, value: 3 },
      { id: 'symbolMix', label: 'Symbol Mix', min: 0, max: 100, step: 1, value: 56 },
      { id: 'hubCount', label: 'Signal Hubs', min: 0, max: 100, step: 1, value: 8 },
      { id: 'linkPulse', label: 'Link Pulse', min: 0, max: 100, step: 1, value: 58 }
    ],
    dna: [
      { id: 'dnaStrands', label: 'Strands', min: 1, max: 5, step: 1, value: 3 },
      { id: 'dnaRadius', label: 'Helix Radius', min: 10, max: 140, step: 1, value: 50 },
      { id: 'dnaAmplitude', label: 'Wave Amp', min: 10, max: 180, step: 1, value: 82 },
      { id: 'dnaSegments', label: 'Segments', min: 36, max: 240, step: 1, value: 132 }
    ],
    orbit: [
      { id: 'orbitRings', label: 'Ring Count', min: 2, max: 16, step: 1, value: 10 },
      { id: 'orbitSpeed', label: 'Orbital Speed', min: 0.1, max: 4, step: 0.1, value: 1.2 },
      { id: 'orbitScale', label: 'Scale', min: 40, max: 180, step: 1, value: 108 }
    ],
    mobius: [
      { id: 'mobiusDensity', label: 'Strip Density', min: 32, max: 320, step: 1, value: 128 },
      { id: 'galaxyPoints', label: 'Galaxy Points', min: 20, max: 520, step: 1, value: 160 },
      { id: 'mobiusRotation', label: 'Rotation', min: 0, max: 4, step: 0.1, value: 1.1 },
      { id: 'mobiusRibbonWidth', label: 'Ribbon Width', min: 4, max: 90, step: 1, value: 30 },
      { id: 'mobiusTwistAmount', label: 'Twist Amount', min: 0, max: 100, step: 1, value: 48 },
      { id: 'mobiusDepthStrength', label: 'Depth Strength', min: 0, max: 100, step: 1, value: 42 },
      { id: 'mobiusSurfaceGrid', label: 'Surface Grid', min: 0, max: 100, step: 1, value: 42 },
      { id: 'mobiusSignalParticles', label: 'Signal Particles', min: 0, max: 160, step: 1, value: 42 },
      { id: 'mobiusSignalSpeed', label: 'Signal Speed', min: 0, max: 100, step: 1, value: 54 },
      { id: 'galaxySpiral', label: 'Galaxy Spiral', min: 0, max: 100, step: 1, value: 48 },
      { id: 'mobiusDustAmount', label: 'Dust Amount', min: 0, max: 220, step: 1, value: 50 },
      { id: 'mobiusGravityPulse', label: 'Gravity Pulse', min: 0, max: 100, step: 1, value: 48 },
      { id: 'mobiusLensDistortion', label: 'Lens Distortion', min: 0, max: 100, step: 1, value: 36 },
      { id: 'mobiusMode', label: 'Mobius Mode', min: 0, max: 4, step: 1, value: 1 }
    ],
    obsidian: [
      { id: 'graphNodes', label: 'Graph Nodes', min: 20, max: 220, step: 1, value: 128 },
      { id: 'graphLinks', label: 'Link Density', min: 0, max: 100, step: 1, value: 50 },
      { id: 'graphDepth', label: 'Graph Depth', min: 0, max: 100, step: 1, value: 60 }
    ],
    missile: [
      { id: 'missileRate', label: 'Fire Rate', min: 0, max: 100, step: 1, value: 48 },
      { id: 'missileCount', label: 'Max Missiles', min: 4, max: 40, step: 1, value: 22 },
      { id: 'fragmentCount', label: 'Fragments', min: 4, max: 80, step: 1, value: 24 },
      { id: 'explosionSize', label: 'Explosion Size', min: 10, max: 160, step: 1, value: 76 },
      { id: 'missileScatter', label: 'Target Scatter', min: 0, max: 100, step: 1, value: 56 },
      { id: 'missileTrailLength', label: 'Trail Length', min: 4, max: 30, step: 1, value: 16 },
      { id: 'missileGuidance', label: 'Guidance Motion', min: 0, max: 100, step: 1, value: 54 },
      { id: 'missileReticleSize', label: 'Reticle Size', min: 6, max: 40, step: 1, value: 16 },
      { id: 'missileEngineFlicker', label: 'Engine Flicker', min: 0, max: 100, step: 1, value: 62 },
      { id: 'launchShockwave', label: 'Launch Shockwave', min: 0, max: 100, step: 1, value: 64 },
      { id: 'targetLockStrength', label: 'Target Lock Strength', min: 0, max: 100, step: 1, value: 60 },
      { id: 'impactWarningPulse', label: 'Impact Warning Pulse', min: 0, max: 100, step: 1, value: 58 },
      { id: 'megaMissilePower', label: 'Mega Missile Power', min: 0, max: 100, step: 1, value: 70 },
      { id: 'clusterSplitAmount', label: 'Cluster Split Amount', min: 2, max: 8, step: 1, value: 4 },
      { id: 'heavyRocketChance', label: 'Heavy Rocket Chance', min: 0, max: 100, step: 1, value: 36 },
      { id: 'debrisAmount', label: 'Debris Amount', min: 0, max: 100, step: 1, value: 54 },
      { id: 'debrisGravity', label: 'Debris Gravity', min: 0, max: 100, step: 1, value: 58 },
      { id: 'debrisLifetime', label: 'Debris Lifetime', min: 0, max: 100, step: 1, value: 56 },
      { id: 'empRadius', label: 'EMP Radius', min: 0, max: 100, step: 1, value: 62 },
      { id: 'empRingCount', label: 'EMP Ring Count', min: 1, max: 6, step: 1, value: 3 },
      { id: 'interferenceStrength', label: 'Interference Strength', min: 0, max: 100, step: 1, value: 48 }
    ],
    laser: [
      { id: 'laserCount', label: 'Beam Count', min: 2, max: 36, step: 1, value: 18 },
      { id: 'laserPerspective', label: 'Perspective', min: 2, max: 4, step: 1, value: 3 },
      { id: 'laserSmoke', label: 'Smoke', min: 0, max: 100, step: 1, value: 24 }
    ],
    chladni: [
      { id: 'chladniDensity', label: 'Grain Density', min: 20, max: 140, step: 1, value: 78 },
      { id: 'chladniModeX', label: 'Mode X', min: 1, max: 10, step: 1, value: 3 },
      { id: 'chladniModeY', label: 'Mode Y', min: 2, max: 12, step: 1, value: 5 },
      { id: 'chladniThreshold', label: 'Node Width', min: 2, max: 100, step: 1, value: 34 },
      { id: 'chladniDrift', label: 'Vibration Drift', min: 0, max: 100, step: 1, value: 46 },
      { id: 'chladniScatter', label: 'Sand Scatter', min: 0, max: 100, step: 1, value: 36 },
      { id: 'chladniLineAlpha', label: 'Line Definition', min: 0, max: 100, step: 1, value: 62 },
      { id: 'chladniSparkle', label: 'Sparkle Amount', min: 0, max: 100, step: 1, value: 54 }
    ],
    chladnicyber: [
      { id: 'cyberChladniDensity', label: 'Grid Density', min: 20, max: 120, step: 1, value: 72 },
      { id: 'cyberChladniModeX', label: 'Mode X', min: 1, max: 10, step: 1, value: 4 },
      { id: 'cyberChladniModeY', label: 'Mode Y', min: 2, max: 12, step: 1, value: 7 },
      { id: 'cyberChladniThreshold', label: 'Node Width', min: 2, max: 100, step: 1, value: 28 },
      { id: 'cyberChladniDrift', label: 'Circuit Drift', min: 0, max: 100, step: 1, value: 52 },
      { id: 'cyberChladniPulse', label: 'Bass Pulse', min: 0, max: 100, step: 1, value: 60 },
      { id: 'cyberChladniCircuit', label: 'Circuit Traces', min: 0, max: 100, step: 1, value: 66 },
      { id: 'cyberChladniSparkle', label: 'Sparkle Amount', min: 0, max: 100, step: 1, value: 58 }
    ],
    slash: [
      { id: 'topoDensity', label: 'Sample Density', min: 24, max: 240, step: 1, value: 128 },
      { id: 'topoLayers', label: 'Band Count', min: 8, max: 56, step: 1, value: 28 },
      { id: 'topoAmplitude', label: 'Spectrum Gain', min: 0, max: 180, step: 1, value: 96 },
      { id: 'topoSpacing', label: 'Band Spacing', min: 8, max: 80, step: 1, value: 22 },
      { id: 'topoDrift', label: 'Scroll Speed', min: 0, max: 100, step: 1, value: 64 },
      { id: 'topoDetail', label: 'High Detail', min: 0, max: 100, step: 1, value: 64 },
      { id: 'topoPulse', label: 'Bass Weight', min: 0, max: 100, step: 1, value: 70 },
      { id: 'topoTracerAmount', label: 'Tracer Amount', min: 0, max: 100, step: 1, value: 60 }
    ],
    atomic: [
      { id: 'atomCount', label: 'Atom Count', min: 4, max: 56, step: 1, value: 18 },
      { id: 'virusCount', label: 'Virus Count', min: 2, max: 28, step: 1, value: 10 },
      { id: 'microParticleAmount', label: 'Micro Particles', min: 10, max: 260, step: 1, value: 120 },
      { id: 'dotSize', label: 'Dot Size', min: 1, max: 24, step: 1, value: 7 },
      { id: 'spreadAmount', label: 'Spread Amount', min: 0, max: 100, step: 1, value: 42 },
      { id: 'largeObjectChance', label: 'Large Object Chance', min: 0, max: 100, step: 1, value: 34 },
      { id: 'driftSpeed', label: 'Drift Speed', min: 0, max: 100, step: 1, value: 46 },
      { id: 'rotationSpeed', label: 'Rotation Speed', min: 0, max: 100, step: 1, value: 54 },
      { id: 'orbitSpeed', label: 'Orbit Speed', min: 0, max: 100, step: 1, value: 58 },
      { id: 'pulseStrength', label: 'Pulse Strength', min: 0, max: 100, step: 1, value: 52 },
      { id: 'wobbleAmount', label: 'Wobble Amount', min: 0, max: 100, step: 1, value: 40 },
      { id: 'bassScaleResponse', label: 'Bass Scale Response', min: 0, max: 100, step: 1, value: 66 },
      { id: 'midRotationResponse', label: 'Mid Rotation Response', min: 0, max: 100, step: 1, value: 62 },
      { id: 'highSparkResponse', label: 'High Spark Response', min: 0, max: 100, step: 1, value: 72 },
      { id: 'beatBurstStrength', label: 'Beat Burst Strength', min: 0, max: 100, step: 1, value: 70 },
      { id: 'coreSize', label: 'Core Size', min: 8, max: 100, step: 1, value: 38 },
      { id: 'spikeLength', label: 'Spike Length', min: 4, max: 48, step: 1, value: 18 },
      { id: 'orbitCount', label: 'Orbit Count', min: 1, max: 6, step: 1, value: 3 },
      { id: 'linkLineAmount', label: 'Link Line Amount', min: 0, max: 100, step: 1, value: 56 },
      { id: 'sceneOpacity', label: 'Scene Opacity', min: 10, max: 100, step: 1, value: 72 },
      { id: 'interactionStrength', label: 'Interaction Strength', min: 0, max: 100, step: 1, value: 60 },
      { id: 'mutationChance', label: 'Mutation Chance', min: 0, max: 100, step: 1, value: 40 },
      { id: 'fusionChance', label: 'Fusion Chance', min: 0, max: 100, step: 1, value: 26 },
      { id: 'swarmChance', label: 'Swarm Chance', min: 0, max: 100, step: 1, value: 38 }
    ],
    iris: [
      { id: 'irisSymmetry', label: 'Symmetry Slices', min: 6, max: 32, step: 1, value: 18 },
      { id: 'irisPetalLength', label: 'Iris Petal Length', min: 15, max: 100, step: 1, value: 58 },
      { id: 'irisAperture', label: 'Pupil Aperture', min: 8, max: 42, step: 1, value: 24 },
      { id: 'irisPrism', label: 'Prism Complexity', min: 0, max: 100, step: 1, value: 72 },
      { id: 'irisRotation', label: 'Iris Rotation', min: 0, max: 100, step: 1, value: 35 },
      { id: 'irisBreathing', label: 'Breathing Pulse', min: 0, max: 100, step: 1, value: 56 },
      { id: 'irisOpacity', label: 'Iris Opacity', min: 0, max: 100, step: 1, value: 42 },
      { id: 'irisGlow', label: 'Iris Glow', min: 0, max: 100, step: 1, value: 18 },
      { id: 'irisPetalMotion', label: 'Petal Motion', min: 0, max: 100, step: 1, value: 54 },
      { id: 'irisMorphSpeed', label: 'Morph Speed', min: 0, max: 100, step: 1, value: 48 },
      { id: 'irisInnerRotation', label: 'Inner Rotation', min: 0, max: 100, step: 1, value: 45 },
      { id: 'irisOuterRotation', label: 'Outer Rotation', min: 0, max: 100, step: 1, value: 35 },
      { id: 'irisPupilPulse', label: 'Pupil Pulse', min: 0, max: 100, step: 1, value: 42 },
      { id: 'irisFibreShimmer', label: 'Fibre Shimmer', min: 0, max: 100, step: 1, value: 55 },
      { id: 'irisSymmetryWarp', label: 'Symmetry Warp', min: 0, max: 100, step: 1, value: 36 },
      { id: 'irisSparkCount', label: 'Spark Particles', min: 20, max: 220, step: 1, value: 120 },
      { id: 'irisFibreDensity', label: 'Iris Fibre Density', min: 0, max: 100, step: 1, value: 64 },
      { id: 'irisPortalDepth', label: 'Portal Depth', min: 0, max: 100, step: 1, value: 62 }
    ],
    firework: [
      { id: 'fireworkRate', label: 'Burst Rate', min: 0, max: 100, step: 1, value: 40 },
      { id: 'fireworkMaxBursts', label: 'Max Bursts', min: 2, max: 24, step: 1, value: 10 },
      { id: 'fireworkSize', label: 'Burst Size', min: 20, max: 180, step: 1, value: 84 },
      { id: 'fireworkScatter', label: 'Scatter', min: 0, max: 100, step: 1, value: 64 },
      { id: 'fireworkLineBurst', label: 'Line Energy', min: 0, max: 100, step: 1, value: 72 },
      { id: 'fireworkShapeMode', label: 'Shape Mode', min: 0, max: 4, step: 1, value: 0 },
      { id: 'fireworkStageDepth', label: 'Stage Depth', min: 0, max: 3, step: 1, value: 0 },
      { id: 'fireworkChildBurstAmount', label: 'Child Bursts', min: 1, max: 10, step: 1, value: 4 },
      { id: 'fireworkDustAmount', label: 'Dust Amount', min: 0, max: 80, step: 1, value: 26 },
      { id: 'fireworkDustSize', label: 'Dust Size', min: 1, max: 20, step: 1, value: 8 },
      { id: 'fireworkMegaSensitivity', label: 'Mega Burst Sense', min: 0, max: 100, step: 1, value: 76 }
    ],
    hybrid: [
      { id: 'hybridMix', label: 'Mix Amount', min: 0, max: 100, step: 1, value: 66 },
      { id: 'hybridSceneDepth', label: 'Layer Depth', min: 0, max: 100, step: 1, value: 70 }
    ]
  },
  perfModes: [
    { name: 'Lite', densityScale: 0.45, glowScale: 0.18, cap: 0.45 },
    { name: 'Balanced', densityScale: 0.68, glowScale: 0.38, cap: 0.68 },
    { name: 'High', densityScale: 0.86, glowScale: 0.6, cap: 0.86 },
    { name: 'Ultra', densityScale: 1.0, glowScale: 0.82, cap: 1.0 }
  ]
};
